In [1]:
import numpy as np

### Generating Random Numbers

In [11]:
r_1 = np.random.randint(1, 20, size=(2))
print(r_1)

[2 8]


In [12]:
r_2 = np.random.randint(1, 20, size=(1, 2))
print(r_2)

[[ 5 16]]


In [13]:
r_3 = np.random.rand(2, 1)
print(r_3)

[[0.65305358]
 [0.22916053]]


In [14]:
r_4 = np.random.randint(20, 100, size=(4, 5))
print(r_4)

[[60 78 97 36 63]
 [49 61 53 36 43]
 [25 21 69 86 40]
 [43 50 89 74 29]]


In [15]:
r_5 = np.random.rand(4, 5)
print(r_5)

[[0.27891692 0.4327779  0.33266883 0.59790141 0.14384192]
 [0.01387847 0.80074456 0.56619375 0.58497467 0.08551542]
 [0.08801943 0.27332177 0.53645426 0.05429035 0.81673661]
 [0.27210493 0.52411452 0.04782847 0.49075918 0.77787285]]


### Generating Random Choices from an Array

In [18]:
students = ['Jennifer', 'Jacob', 'Anthony', 'Symone', 'Zainab', 'Caitlan', 'Hassan', 'Vieri', 'Craig', 'Rodolfo', 'Jaela', 'Kailyn']

In [20]:
call_on = np.random.choice(students)
print(call_on)

Kailyn


In [21]:
breakout_groups = np.random.choice(students, size=(3, 4))
print(breakout_groups)

[['Jennifer' 'Jennifer' 'Vieri' 'Kailyn']
 ['Zainab' 'Zainab' 'Jaela' 'Rodolfo']
 ['Zainab' 'Jaela' 'Caitlan' 'Zainab']]


In [22]:
# This would not be an effective way to assign breakout groups since it repeats students names

In [29]:
call_on_weighted = np.random.choice(students, p=[0.3, 0.1, 0.1, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.1, 0.1, 0.0], size=(5))
# # Explanation of probabilities:
# - Jennifer has a 30% likelihood of being selected.
# - Kailyn has a 0% likelihood, so she will not be chosen.
# - Jacob, Anthony, Rodolfo, and Jaela each have a 10% likelihood.
# - The other students each have a 5% likelihood.
print(call_on_weighted)

['Jennifer' 'Symone' 'Jennifer' 'Zainab' 'Jennifer']


### Generating a Normal Distribution

In [30]:
bell_curve = np.random.normal(loc=10, scale=5, size=(4, 5))
print(bell_curve)

[[13.86795638 -4.64120777 12.40438721  9.06689884 21.16747815]
 [11.63489497  8.89052223  9.79139119  7.40845431 10.06239019]
 [11.41333827 14.9970172   9.05032076 14.68881759  6.36570736]
 [ 8.09373919 12.93174785 12.2708011   2.01198118 16.07456742]]
