# Exercise 2.A NumPy fundamentals 

In [1]:
import numpy as np

## Array Basics

In [2]:
fruits = ['apple', 'banana', 'cherry', 'date']

In [4]:
arr_1 = np.array(fruits)
print(arr_1)

['apple' 'banana' 'cherry' 'date']


In [7]:
arr_1.dtype

dtype('<U6')

In [9]:
# < means little endian byte order so the least significant byte is stored first
# U means Unicode string
# 6 is the max number of character in the unicode string that's stored

In [11]:
arr_2 = np.array([[10, 11, 12], [13, 14, 15]])
print(arr_2)

[[10 11 12]
 [13 14 15]]


In [16]:
print(arr_2.T)

[[10 13]
 [11 14]
 [12 15]]


In [17]:
# Using the transpose atrribute (.T) does not change the values stored in arr_2

In [18]:
arr_3 = np.array([[1, 3, 5], [2, 4, 6]])
print(arr_3)

[[1 3 5]
 [2 4 6]]


In [19]:
arr_4 = np.array([arr_3[0, 2], arr_3[1, 1]])
print(arr_4)

[5 4]


In [20]:
arr_5 = np.array([[[1, 1], [1, 1]], [[1, 1], [1, 1]]])
print(arr_5)

[[[1 1]
  [1 1]]

 [[1 1]
  [1 1]]]


In [23]:
print(arr_5.shape) # using this to confirm that each dimension had 2 values

(2, 2, 2)
