In [1]:
import numpy as np

### Looping Through Arrays

In [3]:
arrA = np.array([[11, 12, 13] , [14, 15, 16]])
print(arrA)

[[11 12 13]
 [14 15 16]]


In [8]:
for x in arrA:
    print(x * 2)

[22 24 26]
[28 30 32]


In [11]:
for x in arrA:
    for y in x:
        print(y * 2)

22
24
26
28
30
32


The first loop resulted in the first dimension of arrA being printed. Since there were 2 arrays in arrA, it printed one array as a row, but we mentioned to multipy the values by 2.
Therefore, it printed 2 arrays with the values multipied by 2

The second loop printed each individual element (same values as the first loop since we still disclosed it to multiply 2), but it printed indivually by line

In [22]:
for x in arrA:
    for y in x:
        loop_result = x * 2
        print(loop_result)
# This resulted in the first array shown 3 times with the values duplicated
# Same for the second array. I think for each value (6 in total) it printed x (1st array and 2nd array)

[22 24 26]
[22 24 26]
[22 24 26]
[28 30 32]
[28 30 32]
[28 30 32]


### Joining and Stacking Arrays

In [24]:
joined_array_1 = np.concatenate((arrA, arrA)) #Concat. on axis=0, default so not specified
print(joined_array_1)

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [26]:
joined_array_2 = np.concatenate((arrA, arrA), axis=1)
print(joined_array_2)

[[11 12 13 11 12 13]
 [14 15 16 14 15 16]]


In [28]:
stacked_array_1 = np.stack((joined_array_1, joined_array_1))
print(stacked_array_1)

[[[11 12 13]
  [14 15 16]
  [11 12 13]
  [14 15 16]]

 [[11 12 13]
  [14 15 16]
  [11 12 13]
  [14 15 16]]]


In [34]:
stacked_array_2 = np.stack((joined_array_1, joined_array_2))

ValueError: all input arrays must have the same shape

In [30]:
# stacked_array_2 produced a ValueError message since the input arrays are diff. shapes

In [32]:
another_joined_array = np.concatenate((joined_array_1, arrA))
print(another_joined_array)

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [33]:
another_2 = np.concatenate((joined_array_1, arrA), axis=1) 

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 4 and the array at index 1 has size 2

In [35]:
# Value Error saying that 1st array has a size 4 and 2nd array has a size 2 
# Has to have same dimensions

In [48]:
horizontal = np.hstack((arrA, arrA))
# hstack() stacks arrays horizontally (side by side), adding columns

vertical = np.vstack((arrA, arrA))
# vstack() stacks arrays vertically (one on top of the other), adding rows

depth = np.dstack((arrA, arrA))
# dstack() stacks arrays along the third axis, creating a 3D array

# displaying results 
print(f'''
Horizontal stacking:
{horizontal}

Vertical stacking:
{vertical}

Depth stacking:
{depth}
''')


Horizontal stacking:
[[11 12 13 11 12 13]
 [14 15 16 14 15 16]]

Vertical stacking:
[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]

Depth stacking:
[[[11 11]
  [12 12]
  [13 13]]

 [[14 14]
  [15 15]
  [16 16]]]



### Splitting Arrays

In [49]:
splitsky = np.array_split(joined_array_1, 2)
print(splitsky)

[array([[11, 12, 13],
       [14, 15, 16]]), array([[11, 12, 13],
       [14, 15, 16]])]


In [50]:
# it splits the joined array into 2 arrays containg 2 rows of 2 dimensions equally

In [51]:
spliterino = np.array_split(joined_array_1, 3)
print(spliterino)

[array([[11, 12, 13],
       [14, 15, 16]]), array([[11, 12, 13]]), array([[14, 15, 16]])]


In [53]:
# Split into 3 arrays, all still 2d arrays
# First array contains the full 2d array with 2 rows
# 2nd & 3rd array was split from the other 2d array, one containing each row

### Searching and Replacing Array Values

In [54]:
result_1 = np.where(arrA % 2 == 0, arrA, 'odd')
print(result_1)

[['odd' '12' 'odd']
 ['14' 'odd' '16']]


### Sorting and Filtering Arrays

In [56]:
arrB = np.array([[7, 6], [13, 5], [7, 3]])

arrB_sorted = np.sort(arrB)

print(arrB_sorted)

[[ 6  7]
 [ 5 13]
 [ 3  7]]


In [60]:
print(f'{arrB} \n')

z = arrB < 7
arrC = arrB[z]

print(arrC)

[[ 7  6]
 [13  5]
 [ 7  3]] 

[6 5 3]


In [63]:
print(f'{arrB} \n')

y = arrB >= 7
arrD = arrB[y]

print(arrD)

[[ 7  6]
 [13  5]
 [ 7  3]] 

[ 7 13  7]
